### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by BikkuMyy** [virtalas/pakkaaja#5]
## Koodikatselmointi 1

Koodi ladattu 19.4.2018 noin klo 21.30

### Yleistä
Mielenkiintoinen aihevalinta, vaikkakin itselle vieras. Aihemäärittely oli selkeä ja sen avulla pääsi jo kärryille. Pahoittelut silti, että en välttämättä osaa antaa kovin tarkkaa palautetta itse pakkaamisen toteutuksesta.

Yritin suorittaa ohjelman (gradle run), mikä aiheutti virheen ```Error: Could not find or load main class pakkaaja.Main```. Kaikki Main-luokkaan liittyvä näytti kuitenkin olevan build.gradlessa kuten pitää. Samasta syystä myöskään jar-tiedoston suoritus ei ollut mahdollista. Muuten gradle build onnistui ja testit menivät läpi. NetBeans ei suostunut projektin kanssa lainkaan yhteistyöhön, mutta luulen, että ongelma oli NetBeanssissa.

### Rakenne
Koodia on paljon, mutta se on helppolukuista ja kattavasti dokumentoitua. Main-luokka on tällä hetkellä aika massiivinen. Kaikki käyttöliittymään liittyvä toiminnallisuus olisi hyvä eriyttää yhteen tai useampaan luokkaan niin, että main-metodissa voidaan vain kutsua itse ohjelman käynnistävää komentoa. Muuten pakettirakenne ja luokkajako ovat selkeät. 

### Testaus
Yksikkötestikattavuus korkea. Pieniä huomioita:
- HuffmanCoderTest-luokan testi ```testCompress()``` ei oikeastaan testaa mitään, luo vain uuden ```MockInStream```-olion..?
- Vähemmän oleellista, mutta kuitenkin: käyttämättömät ```@Before``` ja ```@After``` -metodit jokaisessa testiluokassa särähtivät silmään.

**Comment by virtalas** [comment]
Kiitos palautteesta!

Joo, taisit ladata projektin juuri sellaiseen aikaan jolloin masteriin pääsi livahtamaan huono versio kun muutin projektia ja gradlen toimintaa.
